import { TokenLabel, TokenTypes } from "./parser";
import { IToken } from "chevrotain";
import { parserInstance } from "./parser";
import {
  ImportStatementCstChildren,
  NumericalValueCstChildren,
  PropertyItemCstChildren,
  ListCstChildren,
  ReferenceDeclarationCstChildren,
  RefListCstChildren,
  ArrowPropertyCstChildren,
  ReferencePipeCstChildren,
  AliasClauseCstChildren,
  AssignmentPropertyCstChildren,
  DocumentCstChildren,
  RecordDeclarationCstChildren,
  GraphDeclarationCstChildren,
  CollectionDeclarationCstChildren,
  ReferenceValueCstChildren,
} from "./parser-types";
import {
  CMDLCollection,
  CmdlTree,
  CMDLRecord,
  CMDLGraph,
  CMDLReference,
  CMDLBoolProp,
  CMDLImport,
  CMDLListProp,
  CMDLNumProp,
  CMDLRefProp,
  CMDLRoot,
  CMDLNode,
  CMDLAssignProp,
} from "./cmdl-tree";
import { CMDLEdgeProp, CMDLRefListProp, CMDLStrProp } from "./cmdl-tree/nodes";

export class CMDLToken {
  image: string;
  type: TokenTypes;
  private _label?: TokenLabel;
  startOffset: number;
  startLine?: number;
  endLine?: number;
  startColumn?: number;
  endColumn?: number;
  endOffset?: number;

  constructor(token: IToken) {
    this.image = token.image;
    this.startOffset = token.startOffset;
    this.endOffset = token.endOffset;
    this.startColumn = token.startColumn;
    this.endColumn = token.endColumn;
    this.startLine = token.startLine;
    this.endLine = token.endLine;

    const tokenType = this.isTokenType(token.tokenType.name);

    if (tokenType) {
      this.type = tokenType;
    } else {
      throw new Error(`Unknown token type ${token.tokenType.name}`);
    }
  }

  private isTokenType(arg: string) {
    if (Object.values(TokenTypes).includes(arg as unknown as TokenTypes)) {
      return arg as unknown as TokenTypes;
    } else {
      return undefined;
    }
  }

  get label() {
    return this._label;
  }

  set label(label: TokenLabel | undefined) {
    this._label = label;
  }
}

const BaseVisitor = parserInstance.getBaseCstVisitorConstructor();

/**
 * Class to traverse CST generated by Chevrotain parser and compile an AST representation as a CMDL tree
 */
export class CSTVisitor extends BaseVisitor {
  constructor() {
    super();
    this.validateVisitor();
  }

  /**
   * Constructs CMDL AST
   * @param ctx DocumentCstChildren
   * @returns CMDLtree
   */
  public document(ctx: DocumentCstChildren): CmdlTree {
    const rootNode = new CMDLRoot();
    const tree = new CmdlTree(rootNode);

    if (ctx.importStatement) {
      this.visit(ctx.importStatement, rootNode);
    }

    if (ctx.collectionDeclaration) {
      this.visit(ctx.collectionDeclaration, rootNode);
    }

    if (ctx.recordDeclaration) {
      this.visit(ctx.recordDeclaration, rootNode);
    }

    if (ctx.graphDeclaration) {
      this.visit(ctx.graphDeclaration, rootNode);
    }

    if (ctx.assignmentProperty) {
      this.visit(ctx.assignmentProperty, rootNode);
    }

    return tree;
  }

  /**
   * Evaluates import statements from CST
   * @param ctx ImportStatementCstChildren
   * @param parent CmdlTree
   */
  public importStatement(
    ctx: ImportStatementCstChildren,
    parent: CMDLNode
  ): void {
    let importNode: CMDLImport;
    const importToken = new CMDLToken(ctx.IMPORT[0]);
    const importId = new CMDLToken(ctx.IMPORT_NAME[0]);
    const fromToken = new CMDLToken(ctx.FROM[0]);
    const sourceToken = new CMDLToken(ctx.IMPORT_SOURCE[0]);
    const semicolonToken = new CMDLToken(ctx.SEMICOLON[0]);

    if (ctx.IMPORT_ALIAS) {
      const { asToken, aliasToken } = this.visit(ctx.IMPORT_ALIAS);
      importNode = new CMDLImport(
        importToken,
        importId,
        asToken,
        aliasToken,
        fromToken,
        sourceToken,
        semicolonToken
      );
    } else {
      importNode = new CMDLImport(
        importToken,
        importId,
        fromToken,
        sourceToken,
        semicolonToken
      );
    }

    parent.addChildNode(importNode);
  }

  aliasClause(ctx: AliasClauseCstChildren): {
    asToken: CMDLToken;
    aliasToken: CMDLToken;
  } {
    const asToken = new CMDLToken(ctx.AS[0]);
    const aliasToken = new CMDLToken(ctx.IDENTIFIER[0]);

    return { asToken, aliasToken };
  }

  collectionDeclaration(
    ctx: CollectionDeclarationCstChildren,
    parent: CMDLNode
  ) {
    const collectionToken = new CMDLToken(ctx.COLLECTION[0]);
    const collectionNameToken = new CMDLToken(ctx.COLLECTION_NAME[0]);
    const endToken = new CMDLToken(ctx.END[0]);
    const endName = new CMDLToken(ctx.END_COLLECTION_NAME[0]);

    const collection = new CMDLCollection(
      collectionToken,
      collectionNameToken,
      endToken,
      endName
    );

    parent.addChildNode(collection);

    if (ctx.collectionDeclaration) {
      for (const node of ctx.collectionDeclaration) {
        this.visit(node, collection);
      }
    }

    if (ctx.recordDeclaration) {
      for (const node of ctx.recordDeclaration) {
        this.visit(node, collection);
      }
    }

    if (ctx.graphDeclaration) {
      for (const node of ctx.graphDeclaration) {
        this.visit(node, collection);
      }
    }

    if (ctx.assignmentProperty) {
      for (const node of ctx.assignmentProperty) {
        this.visit(node, collection);
      }
    }
  }

  recordDeclaration(ctx: RecordDeclarationCstChildren, parent: CMDLNode) {
    const recordToken = new CMDLToken(ctx.RECORD[0]);
    const recordNameToken = new CMDLToken(ctx.RECORD_NAME[0]);
    const colonToken = new CMDLToken(ctx.COLON[0]);
    const typeToken = new CMDLToken(ctx.TYPE[0]);
    const lcurl = new CMDLToken(ctx.LCURL[0]);
    const rcurl = new CMDLToken(ctx.RCURL[0]);

    const record = new CMDLRecord(
      recordToken,
      recordNameToken,
      colonToken,
      typeToken,
      lcurl,
      rcurl
    );

    parent.addChildNode(record);

    if (ctx.propertyItem) {
      for (const node of ctx.propertyItem) {
        this.visit(node, record);
      }
    }

    if (ctx.referenceDeclaration) {
      for (const node of ctx.referenceDeclaration) {
        this.visit(node, record);
      }
    }
  }

  graphDeclaration(ctx: GraphDeclarationCstChildren, parent: CMDLNode) {
    const graphToken = new CMDLToken(ctx.GRAPH[0]);
    const graphNameToken = new CMDLToken(ctx.GRAPH_NAME[0]);
    const colonToken = new CMDLToken(ctx.COLON[0]);
    const typeToken = new CMDLToken(ctx.TYPE[0]);
    const lcurl = new CMDLToken(ctx.LCURL[0]);
    const rcurl = new CMDLToken(ctx.RCURL[0]);

    const graph = new CMDLGraph(
      graphToken,
      graphNameToken,
      colonToken,
      typeToken,
      lcurl,
      rcurl
    );

    parent.addChildNode(graph);

    if (ctx.arrowProperty) {
      for (const node of ctx.arrowProperty) {
        this.visit(node, graph);
      }
    }

    if (ctx.propertyItem) {
      for (const node of ctx.propertyItem) {
        this.visit(node, graph);
      }
    }
  }

  referenceDeclaration(ctx: ReferenceDeclarationCstChildren, parent: CMDLNode) {
    const refToken = new CMDLToken(ctx.REFERENCE_NAME[0]);
    const lcurl = new CMDLToken(ctx.LCURL[0]);
    const rcurl = new CMDLToken(ctx.RCURL[0]);

    const pathTokens: CMDLToken[] = [];

    if (ctx.REF_ITEM) {
      let token: CMDLToken;
      for (const subId of ctx.REF_ITEM) {
        token = new CMDLToken(subId);
        pathTokens.push(token);
      }
    }

    const reference = new CMDLReference(refToken, ...pathTokens, lcurl, rcurl);

    parent.addChildNode(reference);

    if (ctx.propertyItem) {
      for (const node of ctx.propertyItem) {
        this.visit(node, reference);
      }
    }
  }

  refValue(ctx: ReferenceValueCstChildren) {
    const refToken = new CMDLToken(ctx.REFERENCE_NAME[0]);

    const pathTokens: CMDLToken[] = [];

    if (ctx.REF_ITEM) {
      let token: CMDLToken;
      for (const subId of ctx.REF_ITEM) {
        token = new CMDLToken(subId);
        pathTokens.push(token);
      }
    }

    return { refToken, pathTokens };
  }

  assignmentProperty(ctx: AssignmentPropertyCstChildren, parent: CMDLNode) {
    const propToken = new CMDLToken(ctx.PROPERTY[0]);
    const propName = new CMDLToken(ctx.PROP_NAME[0]);
    const colonToken = new CMDLToken(ctx.COLON[0]);
    const typeToken = new CMDLToken(ctx.TYPE[0]);
    const assignmentToken = new CMDLToken(ctx.ASSIGNMENT[0]);
    const value = new CMDLToken(ctx.STRING_LITERAL[0]);
    const semicolonToken = new CMDLToken(ctx.SEMICOLON[0]);

    const assignmentProp = new CMDLAssignProp(
      propToken,
      propName,
      colonToken,
      typeToken,
      assignmentToken,
      value,
      semicolonToken
    );

    parent.addChildNode(assignmentProp);
  }

  arrowProperty(ctx: ArrowPropertyCstChildren, parent: CMDLNode) {
    const lAngle = new CMDLToken(ctx.LANGLE[0]);
    const rAngle = new CMDLToken(ctx.RANGLE[0]);
    const arrowToken = new CMDLToken(ctx.ARROW[0]);
    const colonToken = ctx.COLON ? new CMDLToken(ctx.COLON[0]) : undefined;
    const numberToken = ctx.EDGE_VALUE
      ? new CMDLToken(ctx.EDGE_VALUE[0])
      : undefined;

    const lhsValues = this.visit(ctx.lhs);
    const rhsValues = this.visit(ctx.rhs);

    const arrowProp = new CMDLEdgeProp(
      lAngle,
      ...lhsValues.pipeTokens,
      arrowToken,
      ...rhsValues.pipeTokens,
      rAngle,
      colonToken,
      numberToken
    );

    arrowProp.addRefs(lhsValues.refs, "lhs");
    arrowProp.addRefs(rhsValues.refs, "rhs");

    parent.addChildNode(arrowProp);
  }

  referencePipe(ctx: ReferencePipeCstChildren) {
    const pipeTokens: CMDLToken[] = [];
    const refs: CMDLReference[] = [];

    if (ctx.PIPE) {
      for (const token of ctx.PIPE) {
        const pipeToken = new CMDLToken(token);
        pipeTokens.push(pipeToken);
      }
    }

    for (const reference of ctx.referenceValue) {
      const { refToken, pathTokens } = this.visit(reference);
      const ref = new CMDLReference(refToken, ...pathTokens);
      refs.push(ref);
    }
    return { pipeTokens, refs };
  }

  propertyItem(ctx: PropertyItemCstChildren, parent: CMDLNode) {
    const idToken = new CMDLToken(ctx.PROP_NAME[0]);
    const colonToken = new CMDLToken(ctx.COLON[0]);

    if (ctx.numericalValue) {
      const numPropTokens = this.visit(ctx.numericalValue, {
        idToken,
        colonToken,
      });
      const numProp = new CMDLNumProp(...numPropTokens);
      parent.addChildNode(numProp);
    } else if (ctx.list) {
      const listProp = this.visit(ctx.list, { idToken, colonToken });
      parent.addChildNode(listProp);
    } else if (ctx.STR_VALUE) {
      const strToken = new CMDLToken(ctx.STR_VALUE[0]);
      const strProp = new CMDLStrProp(idToken, colonToken, strToken);
      parent.addChildNode(strProp);
    } else if (ctx.referenceValue) {
      const { refToken, pathTokens } = this.visit(ctx.referenceValue);
      const refProp = new CMDLRefProp(
        idToken,
        colonToken,
        refToken,
        ...pathTokens
      );
      parent.addChildNode(refProp);
    } else if (ctx.BOOLEAN_VALUE) {
      const bool = new CMDLToken(ctx.BOOLEAN_VALUE[0]);
      const boolProp = new CMDLBoolProp(idToken, colonToken, bool);
      parent.addChildNode(boolProp);
    } else if (ctx.refList) {
      const refListProp = this.visit(ctx.refList, { idToken, colonToken });
      parent.addChildNode(refListProp);
    } else {
      //! push errors to AST class
    }
  }

  list(ctx: ListCstChildren, parent: CMDLNode) {
    const lSquare = new CMDLToken(ctx.LSQUARE[0]);
    const rSquare = new CMDLToken(ctx.RSQUARE[0]);
    const valueTokens: CMDLToken[] = [];
    const commas: CMDLToken[] = [];

    let token, comma: CMDLToken;
    if (ctx.COMMA) {
      for (const item of ctx.COMMA) {
        comma = new CMDLToken(item);
        commas.push(comma);
      }
    }

    for (const value of ctx.STR_VALUE) {
      token = new CMDLToken(value);
      valueTokens.push(token);
    }

    const listProp = new CMDLListProp(
      lSquare,
      ...valueTokens,
      ...commas,
      rSquare
    );
    parent.addChildNode(listProp);
  }

  refList(ctx: RefListCstChildren, parent: CMDLNode) {
    const lSquare = new CMDLToken(ctx.LSQUARE[0]);
    const rSquare = new CMDLToken(ctx.RSQUARE[0]);
    const refs: CMDLReference[] = [];
    const commas: CMDLToken[] = [];

    let comma: CMDLToken;
    if (ctx.COMMA) {
      for (const item of ctx.COMMA) {
        comma = new CMDLToken(item);
        commas.push(comma);
      }
    }

    if (ctx.referenceValue) {
      for (const ref of ctx.referenceValue) {
        const { refToken, pathTokens } = this.visit(ref);
        const cmdlRef = new CMDLReference(refToken, ...pathTokens);
        refs.push(cmdlRef);
      }
    }

    const reflist = new CMDLRefListProp(lSquare, ...refs, ...commas, rSquare);
    parent.addChildNode(reflist);
  }

  numericalValue(ctx: NumericalValueCstChildren) {
    const valueToken = new CMDLToken(ctx.NUMBER_LITERAL[0]);
    const unitToken = ctx.NUM_UNIT ? new CMDLToken(ctx.NUM_UNIT[0]) : undefined;
    const uncOp = ctx.UNCERTAINTY_OPERATOR
      ? new CMDLToken(ctx.UNCERTAINTY_OPERATOR[0])
      : undefined;
    const uncValue = ctx.UNC_VALUE
      ? new CMDLToken(ctx.UNC_VALUE[0])
      : undefined;

    return [valueToken, unitToken, uncOp, uncValue];
  }
}
