import { IUnit, UNITS } from './unit-types';

export const massUnits: IUnit[] = [
  {
    symbol: UNITS.GG,
    regex: new RegExp(UNITS.GG),
    detail: 'gigagram',
    description: 'mass unit in gigagrams',
    aliases: ['Gigagram', 'gigagram'],
    factor: 1e9,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.M_G,
    regex: new RegExp(UNITS.M_G),
    detail: 'megagram',
    description: 'mass unit in megagrams',
    aliases: ['Megagram', 'megagram'],
    factor: 1e6,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.KG,
    regex: new RegExp(UNITS.KG),
    detail: 'kilogram',
    description: 'mass unit in kilograms',
    aliases: ['kilogram'],
    factor: 1e3,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.HG,
    regex: new RegExp(UNITS.HG),
    detail: 'hectogram',
    description: 'mass unit in hectograms',
    aliases: ['Hectogram', 'hectogram'],
    factor: 1e2,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.DAG,
    regex: new RegExp(UNITS.DAG),
    detail: 'decagram',
    description: 'mass unit in decagrams',
    aliases: ['Decagram', 'decagram'],
    factor: 1e1,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.G,
    regex: new RegExp(UNITS.G),
    detail: 'gram',
    description: 'mass unit in grams',
    aliases: ['gram', 'grams'],
    type: 'mass',
    factor: 1,
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.DG,
    regex: new RegExp(UNITS.DG),
    detail: 'decigram',
    description: 'mass unit in decigrams',
    aliases: ['Decigram', 'decigram'],
    factor: 1e-1,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.CG,
    regex: new RegExp(UNITS.CG),
    detail: 'centigram',
    description: 'mass unit in centigrams',
    aliases: ['Centigram', 'centigram'],
    factor: 1e-2,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.MG,
    regex: new RegExp(UNITS.MG),
    detail: 'milligram',
    description: 'mass unit in milligrams',
    aliases: ['Milligram', 'milligram'],
    factor: 1e-3,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.MCG,
    regex: new RegExp(UNITS.MCG),
    detail: 'microgram',
    description: 'mass unit in micrograms',
    aliases: ['Microgram', 'microgram'],
    factor: 1e-6,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.NG,
    regex: new RegExp(UNITS.NG),
    detail: 'nanogram',
    description: 'mass unit in nanograms',
    aliases: ['Nanogram', 'nanogram'],
    factor: 1e-9,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
  {
    symbol: UNITS.PG,
    regex: new RegExp(UNITS.PG),
    detail: 'picogram',
    description: 'mass unit in picograms',
    aliases: ['Picogram', 'picogram'],
    factor: 1e-12,
    type: 'mass',
    base: UNITS.KG,
    min: 0,
    max: 1.79e308,
  },
];
